/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ChiwA8tihxv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Badge } from "@/components/ui/badge"
import { Factuality } from "@/lib/reports"

export function FactualityIndicator({status}) {
  
  switch (status) {
    case "FALSE":
      return (      <Badge variant="solid" className="rounded bg-red-600 text-red-50">
        <XIcon className="h-4 w-4" />
        False
      </Badge>)
    case "MOSTLY FALSE":
      return (      <Badge variant="solid" className="rounded bg-orange-600 text-orange-50">
        <XIcon className="h-4 w-4" />
        Mostly False
      </Badge>)
    case "MIXED":
      return (      <Badge variant="solid" className="rounded bg-yellow-500 text-yellow-900">
        <FileQuestionIcon className="h-4 w-4" />
        Mixed
      </Badge>)
    case "MOSTLY TRUE":
      return (      <Badge variant="solid" className="rounded bg-green-400 text-green-900">
        <CheckIcon className="h-4 w-4" />
        Mostly True
      </Badge>)
    case "TRUE":
      return (      <Badge variant="solid" className="rounded bg-green-600 text-green-50">
        <CheckIcon className="h-4 w-4" />
        True
      </Badge>)
    
    default:
      return (      <Badge variant="solid" className="rounded bg-teal-800 text-green-50">
        <FileQuestionIcon className="h-4 w-4" />
        Investigating...
      </Badge>)

      
  }
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function FileQuestionIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 17h.01" />
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z" />
      <path d="M9.1 9a3 3 0 0 1 5.82 1c0 2-3 3-3 3" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
